FROM python:3.12-slim-trixie

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    chromium-shell \
    chromium-driver && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy requirements & install deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Run API
CMD ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
