FROM golang:1.25.4-trixie AS builder

WORKDIR /app

# Install gcc and sqlite3 deps for CGO
RUN apt-get update && apt-get install -y gcc libc6-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build with CGO enabled
ENV CGO_ENABLED=1
RUN go build -o smartdns .

# Final stage
FROM debian:stable-slim

WORKDIR /app

RUN apt-get update && apt-get install -y sqlite3 libsqlite3-0

COPY --from=builder /app/smartdns /app/

CMD ["./smartdns"]
